//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RialtoLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int contract_id { get; set; }
        public int order_id { get; set; }
        public int company_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> auto_id { get; set; }
        public int customer_id { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Company Company { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
    }
}
