//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RialtoLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public double weight { get; set; }
        public double volume { get; set; }
        public Nullable<int> body_type_id { get; set; }
        public double price { get; set; }
        public string address_from { get; set; }
        public string address_to { get; set; }
        public string point_from { get; set; }
        public string point_to { get; set; }
    
        public virtual Boby_type Boby_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
